# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3bc41e0c9f91ae85d905b9cb6ac22d2ad06ef633d85d4d7c2f3dbcb7f9a82b66987574f4911b825c23b8272dbc6ac5bb54aa364700513539390537eb64eb2c0

test:
  secret_key_base: 4bf04edcab03122d85a5cd99ca548ac85c575d13473af90cc6ef66fa1ed7970fdd4a1868ab343568f6e0c91ee3c711837de651232d03f854c60bdc0f807a5979

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
